Master:
  InstallPlugins:
    - kubernetes:1.12.3
    - workflow-aggregator:2.5
    - workflow-job:2.24
    - credentials-binding:1.16
    - git:3.9.1
    - google-oauth-plugin:0.6
    - google-source-plugin:0.3
    - blueocean:1.8.0
    - simple-theme-plugin:0.4
  Cpu: "1"
  Memory: "4000Mi"
  JavaOpts: "-Xms3500m -Xmx3500m"
  ServiceType: LoadBalancer
Agent:
  Enabled: false
Persistence:
  Size: 20Gi
NetworkPolicy:
  ApiVersion: networking.k8s.io/v1
rbac:
  install: true
  serviceAccountName: cd-jenkins